@startuml
!include _common.style

title Poker Game (Object)
center footer project #1 - object diagram

object "m: Main" as M {
  result = p1
}

object "h: PokerHand" as H {
}

object "c: Card" as C {
}

object "p: Poker" as P {
}

object "pp: PokerPlayer" as PP {
}

object "l: Player" as L {
}

object "pc: PokerCombination" as PC {
}

object "pr: PokerReferee" as PR {
}

object "e: Error" as E {
}


M --> E
M --> PR
M --> PP
H *--> C
PP --o P
PP --> L
PP --> PC
PC --> H
PP --> H
PR --> PP
@enduml
