@startuml

title Poker Game (Object)
center footer project #1 - object diagram

object "m: Main" as M {
  result = p1
}

object "h: PokerHand" as H {
}

object "c: Card" as C {
}


object "pp: PokerPlayer" as PP {
}

object "p1: Player" as P1 {
}

object "p2: Player" as P2 {
}

object "pc: PokerCombination" as PC {
}

object "pr: PokerReferee" as PR {
}

object "e: Error" as E {
}


M -- E
M -- PR
M -- P1
P1 -- PP
PP -- PC
PC -- H
H -- C

M -- P2
P2 -- PP
PP -- PC
PC -- H
H -- C


@enduml
