@startuml
!include _common.style

title Poker Game (Behavior)
center footer project #1 - sequence diagram

actor "User" as U
participant "_: Main" as M

U -> M: main(args: String[])
activate M
    alt |args| = 2
        create "k: PokerPlayer" as K
        M -> K : new PokerPlayer(args[0])
        K --> M : player1
        M -> K : new PokerPlayer(args[1])
        K --> M : player2
        M -> M: players = new ArrayList<PokerPlayer>()
        M -> M : players = add(player1)
        M -> M : players = add(player2)
        create "r: pokerReferee" as R
        M -> R: new pokerReferee(players)
        R --> M: pokerReferee
        M --> U: getMessage()
    else |else|
        create "s: Scanner" as S
        M -> S: new(stdin)
        M -> S: readLine()
        S --> M: line1
        M -> S: readLine()
        S --> M: line2
        M -> K: new PokerPlayer(line1)
        K --> M: player1
        M -> K: new PokerPlayer(line2)
        K --> M: player2
        M -> S: close()
        destroy S
        M -> M : players = new ArrayList<PokerPlayer>()
        M -> M : players = add(player1)
        M -> M : players = add(player2)

        create "r: pokerReferee" as R
        M -> R: new pokerReferee(players)
        R --> M: pokerReferee
        M --> U: getMessage()
    end
deactivate M
@enduml
